name: Tests
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: v1/${{ runner.os }}/node-16/${{ hashFiles('**/package-lock.lock') }}
          restore-keys: v1/${{ runner.os }}/node-14/
      - name: Install dependencies
        run: npm ci
      - name: npm run hello
        run: npm run hello
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
      - name: npm run visual:baseline:ci
        run: npm run visual:baseline:ci
        env:
          PERCY_BRANCH: master
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
      - name: npm run visual:comparison:ci
        run: npm run visual:comparison:ci
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          PERCY_TARGET_BRANCH: master
          PERCY_BRANCH: staging                   